version: '2.17'

services:
  postgres:
    image: postgres:15
    env_file:
      - .env
    restart: always
    ports:
      - ${DB_POSTGRES_PORT}:${DB_POSTGRES_PORT}
    environment:
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
      POSTGRES_USER: ${DB_POSTGRES_USER}
      POSTGRES_DB: ${DB_POSTGRES_DB_NAME}

  mongo:
    image: mongo:6
    env_file:
      - .env
    restart: always
    ports:
      - ${DB_MONGO_PORT}:${DB_MONGO_PORT}
    environment:
      MONGO_INITDB_DATABASE: ${DB_MONGO_DB_NAME}
